In [31]:
import pandas as pd
df =pd.read_csv('data.csv')

In [33]:
df.isnull().sum()
df.dropna(axis=0,inplace=True)

In [34]:
df.describe()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
count,425,425,425,425,425,425,425,425,425,425,425,425,425
unique,21,13,47,311,2,5,103,51,5,101,38,8,83
top,14/15,LaLiga,Group Stage,04-05-15,H,Real Madrid,Sevilla FC,3:00,LW,90,1:00,Right-footed shot,Karim Benzema
freq,44,200,49,4,240,301,19,31,238,10,68,210,44

In [35]:
df['Type'].unique()

array(['Header', 'Left-footed shot', 'Tap-in', 'Right-footed shot',
       'Long distance kick', 'Counter attack goal',
       'Deflected shot on goal', 'Penalty'], dtype=object)

In [36]:
df['Competition'].value_counts()

Competition
LaLiga                   200
UEFA Champions League    102
Serie A                   48
Premier League            37
Copa del Rey              15
FIFA Club World Cup        5
Saudi Pro League           5
FA Cup                     4
Supercopa                  4
UEFA Super Cup             2
Liga Portugal              1
Supercoppa Italiana        1
Italy Cup                  1
Name: count, dtype: int64

In [37]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
10,03/04,FA Cup,Final,5/22/04,H,Manchester United,Millwall FC,3:00,RW,44,1:00,Header,Gary Neville
14,04/05,Premier League,25,02-01-05,A,Manchester United,Arsenal FC,2:04,RW,54,2:02,Left-footed shot,Ryan Giggs
15,04/05,Premier League,25,02-01-05,A,Manchester United,Arsenal FC,2:04,RW,58,2:03,Tap-in,Ryan Giggs
19,04/05,FA Cup,Semi-Finals,4/17/05,A,Manchester United,Newcastle United,1:04,RW,76,1:04,Right-footed shot,Ruud van Nistelrooy